Repository malonnnn/ServerConfig2, pull requests merged in 2018-03, with the labels that each got.

#83 Create brucewayne.yml
  CommandHelper/LocalPackages/commands/chars/brucewayne.yml
Labels: missing file, missing proofs

#102 Update flashbarryallen.yml
  CommandHelper/LocalPackages/commands/chars/flashbarryallen.yml
Labels: accepted - waiting on other PR

#126 Update technokinesis.yml
  Magic/spells/technokinesis.yml
Labels: ready to go - will merge with author present

#128 Create technokinesiswand.yml
  Magic/wands/technokinesiswand.yml
Labels: ready to go - will merge with author present

#138 Create meilin.yml
  CommandHelper/LocalPackages/commands/chars/meilin.yml
Labels: code typos - waiting on author

#148 Update newtscamander.yml
  CommandHelper/LocalPackages/commands/chars/newtscamander.yml
Labels: code typos - waiting on author
