Repository malonnnn/ServerConfig2, pull requests merged in 2018-04, with the labels that each got.

#161 Update jackfrostriseoftheguardians.yml
  CommandHelper/LocalPackages/commands/chars/jackfrostriseoftheguardians.yml
Labels: accepted - waiting on other PR

#159 Create jackfrostwand.yml
  Magic/wands/jackfrostwand.yml
Labels: WIP

#150 Create killmonger.yml
  CommandHelper/LocalPackages/commands/chars/killmonger.yml
Labels: code typos - waiting on author

#229 Create raphaeltmnt.yml
  CommandHelper/LocalPackages/commands/chars/raphaeltmnt.yml
Labels: code typos - waiting on author

#217 Create subzero.yml
  CommandHelper/LocalPackages/commands/chars/subzero.yml
Labels: code typos - waiting on author

#216 Create punisher.yml
  CommandHelper/LocalPackages/commands/chars/punisher.yml
Labels: code typos - waiting on author

#263 Create jason.yml
  CommandHelper/LocalPackages/commands/chars/jason.yml
Labels: ready to go - will merge with author present
